# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('full_name', models.TextField(max_length=50)),
                ('gender', models.TextField(max_length=50)),
                ('schedule', models.TextField()),
                ('pesel', models.TextField(max_length=11)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('permissions_level', models.IntegerField()),
                ('phone_number', models.TextField(max_length=15)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
