# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
