# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='permissions_level',
            field=models.IntegerField(default=0),
        ),
    ]
