# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('drivers', '0004_auto_20171112_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='schedule',
        ),
        migrations.AddField(
            model_name='driver',
            name='schedule',
            field=models.ManyToManyField(to='regions.Region'),
        ),
    ]
