# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_updated', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('north_west', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='Region.south_east+', to='regions.GeoLocalization')),
                ('south_east', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='regions.GeoLocalization')),
            ],
        ),
    ]
