# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='north_west',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='region_south_east', to='regions.GeoLocalization'),
        ),
        migrations.AlterField(
            model_name='region',
            name='south_east',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='regions.GeoLocalization'),
        ),
    ]
