# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20171217_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='updated_by',
            field=models.CharField(choices=[('GDDKiA', 'GDDKiA'), ('DRV', 'Driver')], max_length=20, null=True),
        ),
    ]
