# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_region_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='updated_by',
            field=models.CharField(choices=[('DRV', 'Driver'), ('GDDKiA', 'GDDKiA')], max_length=20, null=True),
        ),
    ]
