# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
