# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='last_location',
        ),
    ]
