# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[(1, 'Sedan'), (2, 'Hatchback'), (3, 'Kombi'), (4, 'SUV'), (5, 'Truck'), (6, 'Van')], default='1', max_length=10),
        ),
    ]
