# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='coord',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='avail',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='velo',
            new_name='velocity',
        ),
    ]
