# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20171109_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('kombi', 'Kombi'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van')], default='sedan', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='need_repair',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
