# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Warunki jazdy bez utrudnień'), ('3', 'Utrudnione warunki jazdy'), ('8', 'Droga zamknięta')], max_length=50)),
                ('type', models.CharField(choices=[('I02', 'Blokada drogi'), ('I04', 'Inne'), ('I05', 'Rajd'), ('I06', 'Pielgrzymka'), ('I07', 'Zawody sportowe'), ('I08', 'Demonstracja'), ('I09', 'Uroczystość'), ('I10', 'Przejazd ważnej osobistości'), ('I11', 'Przejazd pojazdu nienormatywnego'), ('I12', 'Zwiększone natężenie ruchu'), ('I13', 'Protest'), ('K00', 'Katastrofa budowlana'), ('K01', 'Katastrofa ekologiczna'), ('K02', 'Pożar'), ('K03', 'Inne'), ('K04', 'Powódź'), ('S00', 'Brak informacji'), ('U27', 'Remont mostu'), ('U33', 'Roboty drogowe'), ('U42', 'Inne'), ('R00', 'Zderzenie się pojazdów w ruchu - czołowe'), ('R01', 'Zderzenie się pojazdów w ruchu - boczne'), ('R02', 'Zderzenie się pojazdów w ruchu - tylne'), ('R03', 'Najechanie pojazdu na pieszego'), ('R04', 'Najechanie pojazdu na pojazd unieruchomiony'), ('R05', 'Najechanie pojazdu na drzewo, słup'), ('R06', 'Najechanie pojazdu na zaporę kolejową'), ('R07', 'Najechanie pojazdu na urządzenie drogowe'), ('R08', 'Najechanie pojazdu na zwierzę'), ('R09', 'Wywrócenie się pojazdu'), ('R10', 'Inne'), ('R11', 'Zderzenie się pojazdów w ruchu'), ('R12', 'Wypadnięcie pojazdu z jezdni'), ('R13', 'Wjechanie pojazdu do rowu'), ('R14', 'Awaria pojazdu')], max_length=50)),
                ('result', models.CharField(choices=[('J00', 'Brak informacji'), ('J01', 'Wytyczony objazd'), ('J02', 'Przerwa w ruchu'), ('J03', 'Kierowanie ruchem przez policję'), ('J04', 'Inne'), ('J05', 'Zator drogowy'), ('S00', 'Brak informacji'), ('S02', 'Przerwa w ruchu'), ('S01', 'Wytyczony objazd'), ('S03', 'Kierowanie ruchem przez policję'), ('S04', 'Inne'), ('S05', 'Droga zablokowana'), ('S06', 'Ruch wahadłowy'), ('S07', 'Zablokowany pas ruchu'), ('S08', 'Zablokowana część pasa ruchu'), ('S09', 'Zablokowane pobocze')], max_length=50)),
                ('localization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regions.GeoLocalization')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField()),
                ('send_date', models.DateTimeField()),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regions.GeoLocalization')),
            ],
        ),
    ]
