# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20171109_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.GeoLocalization'),
        ),
    ]
